mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index , name='index' ),
    path('', views.index , name='index' ),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('checklist/',include("testapp.urls", namespace="checklist")),
]

testapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'testapp'

urlpatterns = [
    path('all/',views.CheckListList.as_view(),name='all'),
    # path('all/<int:user_id>/',views.CheckListList,name='all'),
    # path('all/<int:user_id>/',views.CheckListList.as_view(),name='all'),

    # path('',views.CheckListList.as_view(),name='all'),
    path('create/',views.CreateCheckList.as_view(),name='create'),

    # re_path(r"delete/(?P<pk>\d+)/$",views.DeleteCheckList.as_view(),name="delete"),
    path('delete/<int:pk>/',views.DeleteCheckList.as_view(), name='delete'),

    # re_path(r"by/(?P<username>[-\w]+)/$",views.CheckListList.as_view(),name="all"),
    # path("by/<username>/",views.CheckListList.as_view(),name="all"),

    ##########
    path('details/<int:pk>/',views.CheckListDetail.as_view(),name='details'),
    # path('checklistcontent/',views.CheckListItemList.as_view(),name='checklistcontent'),
    # path('checklistcontent/<int:pk>/',views.CheckListItemDetail.as_view(),name='checklistcontent'),
    path('addTask/<int:check_list_pk>/',views.CreateListItem.as_view(),name='createitem'),
    path('updatetask/<int:pk>/',views.UpdateListItem.as_view(), name='updatetask'),
    path('deletetask/<int:pk>/',views.DelteListItem.as_view(), name='deletetask'),
]

testapp/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

import misaka

# from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.

class CheckList(models.Model):
    #related_name replaces the something_set
    user = models.ForeignKey(User ,on_delete=models.CASCADE)
    title = models.CharField(max_length=255, unique=False)
    title_html = models.CharField(max_length=255, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title_html = misaka.html(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("testapp:all")

    # def get_absolute_url(self):
    #     return reverse("testapp:all", kwargs={"username": self.user.username, "pk": self.pk})

        # return reverse("testapp:single",
        # kwargs={"username": self.user.username, "pk": self.pk})

class CheckListItem(models.Model):
    # check_list = ForeignKey(CheckList, related_name="???")
    check_list = models.ForeignKey(CheckList, on_delete=models.CASCADE)
    user = models.ForeignKey(User ,on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    ##########################
    title = models.CharField(max_length=255)
    title_html = models.CharField(max_length=255, editable=False)
    message = models.TextField()
    status = models.BooleanField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title_html = misaka.html(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("testapp:all")

    # def get_absolute_url(self):
    #     return reverse("testapp:single",
    #     kwargs={"username": self.user.username, "pk": self.pk})



















# class CheckListSubItem(models.Model):
#     pass

testapp/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

# from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

def index(request):
    return render(request,'mysite/index.html')

'''
Check List
'''

class CreateCheckList(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title',)
    model = models.CheckList
    # success_url = reverse_lazy('testapp:all')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    # pass

class DeleteCheckList(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.CheckList
    # user = models.User
    select_related = ('user',)
    success_url = reverse_lazy('testapp:all') # ???? i need to pass the user Id

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request,'CheckList Deleted')
        return super().delete(*args,**kwargs)

########################

# def CheckListList(request, user_id):
#     user = get_object_or_404(User, pk=user_id)
#     return render(request, 'testapp/checklist_list.html', {'user': user})

class CheckListList(SelectRelatedMixin, generic.ListView):
    model = models.CheckList
    select_related = ("user",)

    # models.CheckList.objects.all().filter(user__exact=User.pk)
    #
    # def get_queryset(self):
    #     try:
    #         self.checklist_user = User.objects.prefetch_related("checklist").get(
    #             username__iexact=self.kwargs.get("username")
    #         )
    #     except User.DoesNotExist:
    #         raise Http404
    #     else:
    #         return self.checklist_user.checklist.all()
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["checklist_user"] = self.checklist_user
    #     return context

######################

class CheckListDetail(SelectRelatedMixin, generic.DetailView):
    model = models.CheckList
    select_related = ("user",)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

          # return queryset.filter(user__username__iexact=self.kwargs.get("username"))
        # return queryset.filter(user_id=self.request.user.id)

'''
Check List Items
'''
# https://stackoverflow.com/questions/26797979/django-createview-using-primary-key
# https://stackoverflow.com/questions/44128982/how-to-use-createview-for-the-model-that-has-a-primary-key-from-the-first-model
# this # https://stackoverflow.com/questions/59124344/pass-pk-to-createview-form-in-django
class CreateListItem(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ("title", "message","status")
    exclude = ('check_list',)
    model = models.CheckListItem

    def form_valid(self, form):
        check_list = models.CheckList.objects.get(pk=self.kwargs['check_list_pk'])
        # user = self.request.user.id
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.check_list = check_list
        self.object.save()
        return super().form_valid(form)




class DelteListItem(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.CheckListItem
    # user = models.User
    select_related = ('check_list','user')
    # template_name = 'testapp/task_confirm_delete.html'
    success_url = reverse_lazy('testapp:all') # ???? i need to pass the user Id

    # def get_queryset(self):
    #     # search = models.CheckListItem.objects.filter(pk=self.kwargs['pk'])
    #     queryset = super().get_queryset()
    #     return queryset.filter(user_id=self.request.user.id)
    #     return queryset.filter(id=search)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request,'Task Deleted')
        return super().delete(*args,**kwargs)

class CheckListItemList(SelectRelatedMixin, generic.ListView):
    model = models.CheckListItem
    # select_related = ("title", "message","status")
    select_related = ("check_list",)

class CheckListItemDetail(SelectRelatedMixin, generic.DetailView):
    model = models.CheckListItem
    select_related = ("check_list",)

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(
    #         user__username__iexact=self.kwargs.get("username")
    #     )

class UpdateListItem(LoginRequiredMixin, SelectRelatedMixin, generic.UpdateView):
    model = models.CheckListItem
    select_related = ('check_list','user')
    # fields = ("title", "message","status")
    fields = ("status",)
    template_name = 'testapp/update_task.html'




##############################
















# class CreateListSubItem(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
#     pass
#
# class DelteListSubItem(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
#     pass

testapp/templates/testapp/checklist_confirm_delete.html
{% extends "mysite/base.html" %}


{% block content %}
<h3>Are you sure you want to delete this List?</h3>

<form method="POST">
	{% csrf_token %}
	<p>{{ user.id }} | {{ user.username }}</p>
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
</form>

{% endblock %}

testapp/templates/testapp/checklist_detail.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% block content %}

<h3>{{ checklist.title }}</h3>
<a href="{% url 'testapp:createitem' check_list_pk=checklist.id %}">Add a task!</a>
<div class="container">
  <ul>
      {% for listitem in checklist.checklistitem_set.all %}
          <!-- <p> Title: {{ listitem.title }} {{ listitem.text }} | User: {{ checklist.user }} | {{ listitem.id }} </p> -->
          <li>
          <!-- <div class="container"> -->
            <a href="{% url 'testapp:updatetask' pk=listitem.pk %}">Title: {{ listitem.title }} {{ listitem.text }} |
              {% if listitem.status == True %}
                <span class="glyphicon glyphicon-check text-success" aria-hidden="true"></span>
              {% else %}
                <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
              {% endif %}
            </a>
            Message: {{ listitem.message }}
            <a href="{% url 'testapp:deletetask' pk=listitem.pk %}" title="delete" class="btn btn-simple">
              <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
              <span class="text-danger icon-label">Delete</span>
            </a>

          <!-- </div> -->
          </li>
      {% empty %}
          <p>This list is empty</p>
      {% endfor %}
  </ul>
</div>

{% endblock %}

testapp/templates/testapp/checklist_form.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% load bootstrap3 %}
{% block content %}

<h4>Create New Checklist</h4>
<form method="POST" action="#" id="postForm">
	{% csrf_token %}

	{% bootstrap_form form %}

	<input type="submit" value="Create" class="btn btn-primary btn-large">
</form>

{% endblock %}

testapp/templates/testapp/checklist_list.html
<!DOCTYPE html>
<!-- user.checklists.count == 0 -->
<!-- for item in check_list -->
{% extends "mysite/base.html" %}
{% block content %}

    <h3>These are your Lists: </h3>
    <a href="{% url 'testapp:create' %}">Create a new checklist</a>
    <div class="container">
        <!-- <p>{{ user.id }} |</p> -->
        <ul>
            {% for item in user.checklist_set.all %}
            <!-- checklist_list
            user.checklist_set.all  -->
            <div class="container">
              <a href="{% url 'testapp:details' pk=item.pk %}">Title: {{ item.title }} | User: {{ item.user }}</a>
              <a href="{% url 'testapp:delete' pk=item.pk %}" title="delete" class="btn btn-simple">
      					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
      					<span class="text-danger icon-label">Delete</span></a>
            </div>
            {% empty %}
            <p>There are no Lists</p>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

testapp/templates/testapp/checklistitem_confirm_delete.html
{% extends "mysite/base.html" %}


{% block content %}
<h3>Are you sure you want to delete this Task?</h3>

<form method="POST">
	{% csrf_token %}
	<p>{{ user.id }} | {{ user.username }}</p>
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
</form>

{% endblock %}

testapp/templates/testapp/checklistitem_detail.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% block content %}

<h1> This is your Checklist</h1>
<p> {{ user.checklist.title }} | {{ checklist_set.id }}</p>
<p>{{ user.id }}</p>
<a href="{% url 'testapp:createitem' %}">Add a task!</a>
<div class="container">
  <ul>
      {% for listitem in check_list.checklistitem_set.all %}
          <p> Title: {{ listitem.title }} {{ listitem.text }} | User: {{ item.user }} </p>
          <p></p>
          {{ listitem.id }}
      {% empty %}
          <p>This list is empty</p>

      {% endfor %}
  </ul>
</div>

{% endblock %}

testapp/templates/testapp/checklistitem_form.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% load bootstrap3 %}
{% block content %}

<h4>Add a Task</h4>
<form method="POST" action="#" id="postForm">
	{% csrf_token %}

	{% bootstrap_form form %}

	<input type="submit" value="Create" class="btn btn-primary btn-large">
</form>

{% endblock %}

testapp/templates/testapp/checklistitem_list.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% block content %}

<h1> This is your Checklist</h1>
<p> {{ user.checklist.title }} | {{ checklist_set.id }}</p>
<p>{{ user.id }}</p>
<a href="{% url 'testapp:createitem' %}">Add a task!</a>
<div class="container">
  <ul>
      {% for listitem in check_list.checklistitem_set.all %}
          <p> Title: {{ listitem.title }} {{ listitem.text }} | User: {{ item.user }} </p>
          <p></p>
          {{ listitem.id }}
      {% empty %}
          <p>This list is empty</p>

      {% endfor %}
  </ul>
</div>

{% endblock %}

testapp/templates/testapp/update_task.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% load bootstrap3 %}
{% block content %}

<h4>Update Task</h4>
<form method="POST" action="#" id="postForm">
	{% csrf_token %}

	{% bootstrap_form form %}

	<input type="submit" value="Create" class="btn btn-primary btn-large">
</form>

{% endblock %}