accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index , name='index' ),
    path('', views.index , name='index' ),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('checklist/',include("testapp.urls", namespace="checklist")),
]

testapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'testapp'

urlpatterns = [
    path('all/',views.CheckListList.as_view(),name='all'),
    # path('all/<int:user_id>/',views.CheckListList,name='all'),
    # path('all/<int:user_id>/',views.CheckListList.as_view(),name='all'),

    # path('',views.CheckListList.as_view(),name='all'),
    path('create/',views.CreateCheckList.as_view(),name='create'),

    # re_path(r"delete/(?P<pk>\d+)/$",views.DeleteCheckList.as_view(),name="delete"),
    path('delete/<int:pk>/',views.DeleteCheckList.as_view(), name='delete'),

    # re_path(r"by/(?P<username>[-\w]+)/$",views.CheckListList.as_view(),name="all"),
    # path("by/<username>/",views.CheckListList.as_view(),name="all"),

    ##########
    path('details/<int:pk>/',views.CheckListDetail.as_view(),name='details'),
    # path('checklistcontent/',views.CheckListItemList.as_view(),name='checklistcontent'),
    # path('checklistcontent/<int:pk>/',views.CheckListItemDetail.as_view(),name='checklistcontent'),
    path('addTask/<int:check_list_pk>/',views.CreateListItem.as_view(),name='createitem'),
    path('updatetask/<int:pk>/',views.UpdateListItem.as_view(), name='updatetask'),
    path('deletetask/<int:pk>/',views.DelteListItem.as_view(), name='deletetask'),
]

templates/mysite/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">
            <a class="navbar-brand mynav" href="{% url 'index' %}">Home</a>
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <!-- user.id -->
                      <li><a href="{% url 'testapp:all' %}" class="btn btn-simple">CheckList</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        <div class="container mycontent jumbotron">
          {% block content %}
          {% endblock %}
        </div>
  </body>

</html>

templates/mysite/index.html
<!DOCTYPE html>
{% extends "mysite/base.html" %}
{% block content %}

    <h1>Welcome to the Index page!</h1>

{% endblock %}